# This file configures the analyzer to enforce code quality standards
# following Clean Architecture and Flutter best practices.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Treat invalid assignments as errors
    invalid_assignment: error

linter:
  rules:
    # Performance & Efficiency
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - sized_box_for_whitespace

    # Code Quality
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - prefer_single_quotes
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - directives_ordering

    # Naming Conventions
    - camel_case_types
    - library_names
    - file_names
    - non_constant_identifier_names
    - constant_identifier_names

    # Documentation
    - package_api_docs
    - public_member_api_docs

    # Error Handling
    - only_throw_errors
    - use_rethrow_when_possible

    # Functional Programming
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals

    # Type Safety
    - always_specify_types
    - avoid_dynamic_calls

    # Flutter Specific
    - use_build_context_synchronously
    - use_decorated_box
    - use_colored_box
